# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dstolz <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/07/25 20:52:18 by dstolz            #+#    #+#              #
#    Updated: 2016/07/25 20:52:22 by dstolz           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

LIB = libft.a

all: comp

comp:
	gcc -c -Wall -Wextra -Werror main.c -o 'do-op'




clean:
	rm -f 

fclean: clean
	rm -f $(NAME)

re: fclean all
